### ISSUE TITLE
Escriptize ltool?

### ISSUE THREAD

**Issue by arpunk** [lfe-rebar3/ltool#1]
Hi @oubiwann, it's been a long time

Do you have plans to escriptize `ltool`? Is `ltool` mean to provide a wrapper to the LFE rebar3 plugins or do you have something else in mind?

**Comment by oubiwann** [comment]
It has! Good to hear from you :-)

I haven't figured out what the final form of ltool is going to be. I'm starting off with a simple lfe script which parses command line args and makes a call out to rebar3. I'm going to see where that goes. 

I've considered the possibility of escriptizing it, but there's lots I need to experiment with first ... but I'm hopeful we'll end up with a standalone binary like `rebar3`.

**Comment by arpunk** [comment]
Hey @oubiwann, yea I've been busy as hell this last few months. I hope I can speed up where I left pretty soon.

Regarding the escript, we can generate it with this rebar config:

```
diff --git a/rebar.config b/rebar.config
index 0ef936b..1748780 100644
--- a/rebar.config
+++ b/rebar.config
@@ -1,3 +1,5 @@
+{artifacts, ["{{profile_dir}}/bin/ltool"]}.
+{escript_name, ltool}.
 {lfe_first_files, []}.
 {eunit_compile_opts, [
    {src_dirs, ["test"]}
@@ -16,5 +18,6 @@
   ]}.

 {provider_hooks, [
-   {pre, [{compile, {lfe, compile}}]}
+   {pre, [{compile, {lfe, compile}}]},
+   {post, [{compile, escriptize}]}
   ]}.
diff --git a/src/ltool.lfe b/src/ltool.lfe
index 81c495a..2da5e0d 100644
--- a/src/ltool.lfe
+++ b/src/ltool.lfe
@@ -1,5 +1,5 @@
 (defmodule ltool
   (export all))

-(defun my-adder (x y)
-  (+ x (+ y 1)))
+(defun main (args)
+  (lfe_io:format "Welcome ~n" '()))
```

We would then need a `main/1` function to be called when the app loads. I've been testing with rebar3 templates and got some stuff [here](https://github.com/arpunk/rebar3_lfe_templates). I'm going to get up to speed on the rebar3 plugins you've been written as I think this is the golden path.

Thank you so much for keeping the hacking alive.

**Comment by oubiwann** [comment]
I've just tried this out -- works like a charm, thanks!

Will commit with you as author ...

**Comment by oubiwann** [comment]
Done in 04d84c48a7f2ce3701e4a2bb36b5466a7cf9bb6f.

Thanks!
