### ISSUE TITLE
Add rebar3 wrapper

### ISSUE THREAD

**Issue by oubiwann** [lfe-rebar3/ltool#3]
We can probably do this without any cli parsing (i.e, not a dependency of issue #2).

The following need to be wrapped:
- [x] `rebar3 help lfe`
- [x] `rebar3 help lfe <task>`
- [x] `rebar3 lfe clean`
- [x] `rebar3 lfe compile`
- [ ] `rebar3 lfe repl`
- [ ] `rebar3 lfe test`
- [x] `rebar3 lfe version`

**Comment by oubiwann** [comment]
Issues:
- `ltool compile` -- output is only generated once the entire compile has been completed ... it would be nice to stream this to stdout
- `ltool repl` -- `os:cmd` waits for output, so this doesn't work
- `ltool test` -- requires additional setup (see the `check` make target)

**Comment by yurrriq** [comment]
Re: `ltool compile`. Maybe we can tie into `rebar_api` somehow and intercept the would-be debug output.

**Comment by yurrriq** [comment]
Looks like [it boils down to an `io:format/2`](https://github.com/erlware/erlware_commons/blob/master/src/ec_cmd_log.erl#L196) call. Maybe we could reroute stdout or just call our own log fun in `lfe-compile`. It might good to wrap `rebar_api:debug` calls in our own logging function that also returns `LogLevel`, `Format` and `Data` or something.

**Comment by yurrriq** [comment]
I've asked about capturing log calls in the rebar channel on IRC and will report back if I hear anything.

**Comment by oubiwann** [comment]
This tool's work has been superseded by https://github.com/lfe-rebar3/rebar3_lfe
